### ISSUE TITLE
Needs some setup before use

### ISSUE THREAD

**Issue by ConnorBar** [agarmu/datamine-scraper#1]
This is a cool project! I checked it out but when I was downloading it to test, `tdmscrape` did not work out of the box. I needed to go into `go/bin` directory to use the executable `./datamine-scraper <url>` If I wanted to use `tdmscrape` from any directory, I needed to create an alias myself: 

`alias tdmscrape="~/go/bin/datamine-scraper"`

Let me know if I did something incorrectly when setting it up.

**Comment by agarmu** [comment]
Setting the PATH is part of installing Go- it should have walked you through adding ~/go/bin to your PATH variable. This is part of go as a language and not an issue specific to tdmscrape. [This](https://www.developer.com/languages/getting-started-with-go-programming/#:~:text=The%20GOPATH%20may%20contain%20multiple,such%20as%20%24GOROOT%2Fbin.) is a good website for more info
